version: "3.8"
services:
  # Spark goes here
  spark-master:
    image: bitnami/spark:3.2.1
    user: root
    container_name: spark-master
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.15
    ports:
      - "7077:7077"
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark-jobs:/spark-jobs:rw
      - spark-events:/tmp/spark-events

  spark-worker-01:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-01
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.16
    hostname: spark-worker-01
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - spark-jobs:/spark-jobs:rw

  spark-worker-02:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-02
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.17
    hostname: spark-worker-02
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - spark-jobs:/spark-jobs:rw

  spark-worker-03:
    image: bitnami/spark:3.2.1
    container_name: spark-worker-03
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.18
    hostname: spark-worker-03
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - spark-jobs:/spark-jobs:rw

  # Elastic goes here
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.21
    hostname: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.22
    hostname: kibana
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://kibana:5601
    depends_on:
      - elasticsearch

networks:
  cluster-network:
    name: cluster-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1


volumes:
  spark-jobs:
    name: spark-jobs
    driver: local
  spark-events:
    name: spark-events
    driver: local
  elastic-data:
    name: elastic-data
    driver: local
