version: "3.8"

services:
  airflow:
    image: bitnami/airflow:2.3.2
    user: root
    container_name: airflow
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.22
    hostname: airflow
    environment:
      - AIRFLOW_DATABASE_HOST=postgres-airflow
      - AIRFLOW_DATABASE_PORT_NUMBER=5432
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_USERNAME=admin
      - AIRFLOW_PASSWORD=admin
      - AIRFLOW_FIRSTNAME=Quân
      - AIRFLOW_LASTNAME=Nguyễn
      - AIRFLOW_EMAIL=admin@airflow.com
    volumes:
      - airflow-data:/bitnami

  airflow-scheduler:
    image: bitnami/airflow-scheduler:2.3.2
    user: root
    container_name: airflow-scheduler
    restart: on-failure
    networks:
      - cluster-network
    hostname: airflow-scheduler
    environment:
      - AIRFLOW_DATABASE_HOST=postgres-airflow
      - AIRFLOW_DATABASE_PORT_NUMBER=5432
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow-scheduler-data:/bitnami

  airflow-worker:
    image: bitnami/airflow-worker:2.3.2
    user: root
    container_name: airflow-worker
    restart: on-failure
    networks:
      - cluster-network
    hostname: airflow-worker
    environment:
      - AIRFLOW_DATABASE_HOST=postgres-airflow
      - AIRFLOW_DATABASE_PORT_NUMBER=5432
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow-worker-data:/bitnami

  postgres-airflow:
    image: bitnami/postgresql:14.3.0
    user: root
    container_name: postgres-airflow
    restart: on-failure
    networks:
      - cluster-network
    hostname: postgres-airflow
    environment:
      - POSTGRESQL_DATABASE=airflow
      - POSTGRESQL_USERNAME=airflow
      - POSTGRESQL_PASSWORD=airflow
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - postgres-airflow-data:/bitnami/postgresql

  redis:
    image: bitnami/redis:7.0.2
    user: root
    container_name: redis
    restart: on-failure
    networks:
      - cluster-network
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami

networks:
  cluster-network:
    name: cluster-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  redis-data:
    name: redis-data
    driver: local
  postgres-airflow-data:
    name: postgres-airflow-data
    driver: local
  airflow-worker-data:
    name: airflow-worker-data
    driver: local
  airflow-scheduler-data:
    name: airflow-scheduler-data
    driver: local
  airflow-data:
    name: airflow-data
    driver: local
