version: "3.8"

services:
  # Kafka goes here
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.10
    hostname: zookeeper
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.2.0
    container_name: kafka
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.11
    hostname: kafka
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://172.18.0.11:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper

  kafka-manager:
    image: hlebalbau/kafka-manager:3.0.0.5
    container_name: kafka-manager
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.12
    hostname: kafka-manager
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    depends_on:
      - "zookeeper"
      - "kafka"

  # Databases go here
  postgres:
    image: postgres:14.3
    container_name: postgres
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.13
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  namenode:
    image: fatcat2me/hadoop-namenode:3.3.3
    container_name: namenode
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.14
    hostname: namenode
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=HADOOP-CLUSTER
    env_file:
      - ./hadoop.env

  datanode:
    image: fatcat2me/hadoop-datanode:3.3.3
    container_name: datanode
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.15
    hostname: datanode
    volumes:
      - datanode-data:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  spark-master:
    image: bitnami/spark:3.2.1
    user: root
    container_name: spark-master
    restart: always
    networks:
      cluster-network:
        ipv4_address: 172.18.0.16
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      
  spark-worker:
    image: bitnami/spark:3.2.1
    user: root
    container_name: spark-worker
    restart: always
    networks:
      cluster-network:
        ipv4_address: 172.18.0.17
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master

  nifi:
    image: apache/nifi:1.16.2
    container_name: nifi
    user: root
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.18
    hostname: nifi
    volumes:
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-logs:/opt/nifi/nifi-current/logs
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=30 sec
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nifi:8080/nifi/" ]
      interval: 30s
      timeout: 20s
      retries: 3
      
  elasticsearch:
    image: bitnami/elasticsearch:8.2.2
    container_name: elasticsearch
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.19
    hostname: elasticsearch
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
      
  kibana:
    image: docker.io/bitnami/kibana:8.2.2
    container_name: kibana
    restart: on-failure
    networks:
      cluster-network:
        ipv4_address: 172.18.0.20
    hostname: kibana
    volumes:
      - kibana-data:/bitnami/kibana
    depends_on:
      - elasticsearch

  # Monitoring goes here
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    container_name: cadvisor
    user: root
    restart: always
    networks:
      cluster-network:
        ipv4_address: 172.18.0.21
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  cluster-network:
    name: cluster-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  zookeeper-data:
    name: zookeeper-data
    driver: local
  kafka-data:
    name: kafka-data
    driver: local
  postgres-data:
    name: postgres-data
    driver: local
  namenode-data:
    name: namenode-data
    driver: local
  datanode-data:
    name: datanode-data
    driver: local
  nifi-database:
    name: nifi-database
    driver: local
  nifi-flowfile:
    name: nifi-flowfile
    driver: local
  nifi-content:
    name: nifi-content
    driver: local
  nifi-provenance:
    name: nifi-provenance
    driver: local
  nifi-state:
    name: nifi-state
    driver: local
  nifi-logs:
    name: nifi-logs
    driver: local
  elasticsearch-data:
    name: elasticsearch-data
    driver: local
  kibana-data:
    name: kibana-data
    driver: local
